planner_frequency: 1.0
controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  # max_vel_theta: 0.3
  # min_vel_theta: 0.1
  max_rotational_vel: 0.3
  # min_rotational_vel: 0.1
  min_in_place_rotational_vel: 0.3
  # escape_vel: -1.5
  backup_vel: -0.2
  
  pdist_scale: 1.0
  sim_time: 2.0
  path_distance_bias: 0.6
  goal_distance_bias: 0.6
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.30
  latch_xy_goal_tolerance: true
  #heading_lookahead: 0.3
  #num_window_points: 10
  holonomic_robot: false



#Real robot params:
##planner_frequency: 1.0
##controller_frequency: 20.0
##
##TrajectoryPlannerROS:
##  max_vel_x: 0.4
##  min_vel_x: 0.1
##  max_vel_theta: 0.4
##  min_vel_theta: -0.4
##  min_in_place_vel_theta: 0.4
##
##  yaw_goal_tolerance: 0.3
##  xy_goal_tolerance: 0.2
##  latch_xy_goal_tolerance: true
##
##  #sim_time: 2.0
##  #path_distance_bias: 0.6
##  #goal_distance_bias: 0.6
##
##  #acc_limit_th: 3.2
##  #acc_limit_x: 2.5
##  #acc_limit_y: 2.5
##  
##  escape_vel: -0.2
##  holonomic_robot: false
